sudo: required
services:
  - docker
before_install:
  - docker build -t ryan801/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ryan801/docker-react npm run test

language: generic

deploy:
  #instructions for deploying successfully tested code to aws
  provider: elasticbeanstalk

	#in ebs copy url http://docker-env.dyunjqy4px.us-west-2.elasticbeanstalk.com/, and paste in region
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"

  bucket_name: "elasticbeanstalk-us-west-2-010037563637"
  bucket_path: "docker"
  on:
    branch: master

#api keys 
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"